"""Select and freeze the agent tasks into ``tasks.json``.

A task = "convert this one source file into the target schema". We only use
*solvable* tasks — source files where at least one parser succeeds — so a failure
is attributable to the agent, not to an impossible input. Solvability, the set of
parsers that work, and the source files all come from the parser-reliability
benchmark (``benchmarks/results.csv`` + ``benchmarks/dataset.json``); the
reference answer is generated by the richest succeeding parser via
``ground_truth.best_reference``.

We task on each entry's NOMAD-designated ``mainfile`` (the primary output), one
per entry, giving a program-diverse set.

Usage:
    python -m agent_study.tasks --out agent_study/tasks.json
"""

from __future__ import annotations

import argparse
import csv
import json
import os
from collections import defaultdict
from typing import Any, Dict, List

from agent_study.complexity import format_level
from agent_study.ground_truth import union_reference

PARSERS = ["ase", "cclib", "gaussian", "iodata"]


def _load_results(path: str) -> Dict[tuple, Dict[str, str]]:
    """Map (entry_id, file) -> {parser: outcome} for mainfiles only."""
    by_file: Dict[tuple, Dict[str, str]] = defaultdict(dict)
    with open(path) as f:
        for r in csv.DictReader(f):
            if r["is_mainfile"] == "1":
                by_file[(r["entry_id"], r["file"])][r["parser"]] = r["outcome"]
    return by_file


def build_tasks(results_csv: str, dataset_json: str, data_root: str,
                max_hard: int) -> List[Dict[str, Any]]:
    """Tasks come in two tiers:

    * ``easy`` — mainfiles where >=1 parser succeeds. Full field-level scoring
      against a union reference.
    * ``hard`` — mainfiles where NO parser succeeds (the discriminating regime:
      the agent must combine parsers or write its own). Scored on behaviour and
      self-consistency; the union reference may be partial or empty.

    Hard tasks are capped and sampled program-diverse to bound sweep cost.
    """
    by_file = _load_results(results_csv)
    with open(dataset_json) as f:
        entries = {e["entry_id"]: e for e in json.load(f)["entries"]}

    easy: List[Dict[str, Any]] = []
    hard: List[Dict[str, Any]] = []
    for (entry_id, rel), outcomes in sorted(by_file.items()):
        program = entries.get(entry_id, {}).get("program_name") or "unknown"
        source = os.path.join(data_root, entry_id, rel)
        winners = [p for p in PARSERS if outcomes.get(p) == "success"]
        candidates = winners or PARSERS
        reference = union_reference(source, candidates, program) or {}
        record = {
            "task_id": f"{program}__{entry_id[:8]}",
            "entry_id": entry_id,
            "program": program,
            "source_file": source,
            "source_basename": os.path.basename(rel),
            "format_level": format_level(program, rel),
            "tier": "easy" if winners else "hard",
            "parser_success": {p: outcomes.get(p) == "success" for p in PARSERS},
            "reference_parsers": reference.pop("_reference_parsers", []),
            "reference": reference,
        }
        (easy if winners else hard).append(record)

    # Sample hard tasks round-robin by program for diversity, up to max_hard.
    by_prog: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for t in hard:
        by_prog[t["program"]].append(t)
    sampled_hard: List[Dict[str, Any]] = []
    progs = sorted(by_prog)
    while len(sampled_hard) < max_hard and any(by_prog[p] for p in progs):
        for p in progs:
            if by_prog[p] and len(sampled_hard) < max_hard:
                sampled_hard.append(by_prog[p].pop(0))
    return easy + sampled_hard


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", default="benchmarks/results.csv")
    ap.add_argument("--dataset", default="benchmarks/dataset.json")
    ap.add_argument("--data-root", default="tests/.data")
    ap.add_argument("--out", default="agent_study/tasks.json")
    ap.add_argument("--max-hard", type=int, default=12, help="cap on hard-tier tasks")
    args = ap.parse_args()

    tasks = build_tasks(args.results, args.dataset, args.data_root, args.max_hard)
    with open(args.out, "w") as f:
        json.dump({"n_tasks": len(tasks), "tasks": tasks}, f, indent=2)

    by_tier: Dict[str, int] = defaultdict(int)
    by_level: Dict[str, int] = defaultdict(int)
    for t in tasks:
        by_tier[t["tier"]] += 1
        by_level[t["format_level"]] += 1
    print(f"Wrote {args.out}: {len(tasks)} tasks "
          f"({dict(by_tier)}, levels {dict(sorted(by_level.items()))}).")


if __name__ == "__main__":
    main()
